import { Cell, CellType } from '../types/game';

export const BOARD_CELLS: Cell[] = [
  { id: 0, name: 'АИРДРОП', type: CellType.SPECIAL, description: 'Получите базовое вознаграждение. Впрыск ликвидности для всех участников сети.' },
  { id: 1, name: 'KEK', price: 60, rent: 2, type: CellType.ASSET, color: '#8B4513', description: 'Высокая волатильность аудитории. Минимальные затраты на поддержку, базовый органический рост.', logoUrl: '/logos/kek.png' },
  { id: 2, name: 'ВЗЛОМ', type: CellType.CHANCE, color: '#AF52DE', description: 'Обнаружена уязвимость в системе. Инициирована случайная сетевая операция.', logoUrl: '/logos/vzlom.png' },
  { id: 3, name: 'SCOOP', price: 60, rent: 4, type: CellType.ASSET, color: '#8B4513', description: 'Стабильный поток трафика. Ценный актив для информационного арбитража.', logoUrl: '/logos/scoop.png' },
  { id: 4, name: 'КОМИССИЯ СЕТИ', type: CellType.TAX, color: '#FF3B30', description: 'Обязательные расходы на поддержку инфраструктуры. Списание 200 токенов.', logoUrl: '/logos/komset.png' },
  { id: 5, name: 'VEIL', price: 200, rent: 25, type: CellType.ASSET, color: '#707070', description: 'Ядро инфраструктуры. Увеличивает охват сети и ваше влияние.', logoUrl: '/logos/veil.png' },
  { id: 6, name: 'SCRAPE', price: 100, rent: 6, type: CellType.ASSET, color: '#87CEEB', description: 'Инструмент автоматического сбора данных. Позволяет эффективно масштабировать операции.', logoUrl: '/logos/scrape.png' },
  { id: 7, name: 'ИНСАЙД', type: CellType.CHANCE, color: '#AF52DE', description: 'Утечка конфиденциальной информации. Возможность для манипуляции рынком.', logoUrl: '/logos/insid.png' },
  { id: 8, name: 'SCALP', price: 100, rent: 6, type: CellType.ASSET, color: '#87CEEB', description: 'Алгоритмический модуль исполнения сделок. Генерирует стабильную микро-прибыль.', logoUrl: '/logos/scalp.png' },
  { id: 9, name: 'BOLT', price: 120, rent: 8, type: CellType.ASSET, color: '#87CEEB', description: 'Функция опережения транзакций включена. Захват ранней ликвидности.', logoUrl: '/logos/bolt.png' },
  { id: 10, name: 'ТЕНЕВОЙ БАН', type: CellType.SPECIAL, description: 'Алгоритмы пометили ваш аккаунт. Доступ к основной сети временно ограничен.' },
  { id: 11, name: 'GLITCH', price: 140, rent: 10, type: CellType.ASSET, color: '#FF69B4', description: 'Легендарная цифровая личность. Высокий статус в экосистеме.', logoUrl: '/logos/glitch.png' },
  { id: 12, name: 'ИНСАЙД', type: CellType.CHANCE, color: '#AF52DE', description: 'Критическая уязвимость протокола. Получен ранний доступ к информации.', logoUrl: '/logos/insid.png' },
  { id: 13, name: 'PRIMATE', price: 140, rent: 10, type: CellType.ASSET, color: '#FF69B4', description: 'Актив культуры "Ape-in". Представляет социальный капитал и доступ в закрытые группы.', logoUrl: '/logos/primate.png' },
  { id: 14, name: 'ZEN', price: 160, rent: 12, type: CellType.ASSET, color: '#FF69B4', description: 'Утонченные эстетические токены. Высокая ценность в нишевых подсетях.', logoUrl: '/logos/zen.png' },
  { id: 15, name: 'SHIELD', price: 200, rent: 25, type: CellType.ASSET, color: '#707070', description: 'Инфраструктура приватности. Необходима для работы в зонах ограниченного доступа.', logoUrl: '/logos/shield.png' },
  { id: 16, name: 'GATE', price: 180, rent: 14, type: CellType.ASSET, color: '#FF8C00', description: 'Нативная идентификация на платформе. Короткое, чистое и узнаваемое имя.', logoUrl: '/logos/gate.png' },
  { id: 17, name: 'ВЗЛОМ', type: CellType.CHANCE, color: '#AF52DE', description: 'Выполнение брутфорс-атаки... Анализ уязвимых конечных точек.', logoUrl: '/logos/vzlom.png' },
  { id: 18, name: 'LINK', price: 180, rent: 14, type: CellType.ASSET, color: '#FF8C00', description: 'Упрощенная адресация. Высокий спрос со стороны институциональных игроков.', logoUrl: '/logos/link.png' },
  { id: 19, name: 'UNION', price: 200, rent: 16, type: CellType.ASSET, color: '#FF8C00', description: 'Имя, готовое к управлению. Критически важно для децентрализованных организаций.', logoUrl: '/logos/union.png' },
  { id: 20, name: 'ИНСАЙД', type: CellType.CHANCE, color: '#AF52DE', description: 'Сетевой узел перегружен. Задержка пакетов. Анализ сетевого трафика на наличие аномалий.', logoUrl: '/logos/insid.png' },
  { id: 21, name: 'FLUX', price: 220, rent: 18, type: CellType.ASSET, color: '#FF0000', description: 'Модуль децентрализованного обмена. Обеспечивает базовую торговую функциональность.', logoUrl: '/logos/flux.png' },
  { id: 22, name: 'ИНСАЙД', type: CellType.CHANCE, color: '#AF52DE', description: 'Прямая передача из ядра администрирования. Расшифровка данных...', logoUrl: '/logos/insid.png' },
  { id: 23, name: 'TIDE', price: 220, rent: 18, type: CellType.ASSET, color: '#FF0000', description: 'Протокол автоматического маркет-мейкера. Жизненно важен для обмена активами.', logoUrl: '/logos/tide.png' },
  { id: 24, name: 'SPAN', price: 240, rent: 20, type: CellType.ASSET, color: '#FF0000', description: 'Межсетевой конвейер. Позволяет перемещать цифровой капитал между сетями.', logoUrl: '/logos/span.png' },
  { id: 25, name: 'VAULT', price: 200, rent: 25, type: CellType.ASSET, color: '#707070', description: 'Корпоративное хранилище. Содержит петабайты зашифрованных данных.', logoUrl: '/logos/vault.png' },
  { id: 26, name: 'HASH', price: 260, rent: 22, type: CellType.ASSET, color: '#FFFF00', description: 'Энергоэффективная майнинг-ферма. Подходит для поддержания стабильного хешрейта.', logoUrl: '/logos/hash.png' },
  { id: 27, name: 'MINT', price: 260, rent: 22, type: CellType.ASSET, color: '#FFFF00', description: 'Высокопроизводительные вычисления. Доминирует в обнаружении локальных блоков.', logoUrl: '/logos/mint.png' },
  { id: 28, name: 'ВЗЛОМ', type: CellType.CHANCE, color: '#AF52DE', description: 'Перехват сессии в процессе... Целевой игрок под воздействием эксплуатации.', logoUrl: '/logos/vzlom.png' },
  { id: 29, name: 'VOLT', price: 280, rent: 24, type: CellType.ASSET, color: '#FFFF00', description: 'Специализированное оборудование для хеширования. Пиковая промышленная эффективность.', logoUrl: '/logos/volt.png' },
  { id: 30, name: 'ОБНАРУЖЕН', type: CellType.SPECIAL, description: 'Власти отследили ваш IP. Требуется немедленная релокация ресурсов.' },
  { id: 31, name: 'BLOOM', price: 300, rent: 26, type: CellType.ASSET, color: '#008000', description: 'Капитал ранних стадий. Инвестирует в протоколы нового поколения.', logoUrl: '/logos/bloom.png' },
  { id: 32, name: 'YIELD', price: 300, rent: 26, type: CellType.ASSET, color: '#008000', description: 'Фонд финансовых инноваций. Высокорисковые портфели с огромной доходностью.', logoUrl: '/logos/yield.png' },
  { id: 33, name: 'ИНСАЙД', type: CellType.CHANCE, color: '#AF52DE', description: 'Замечено движение "китов". Ожидается сильное влияние на рынок.', logoUrl: '/logos/insid.png' },
  { id: 34, name: 'BRAIN', price: 320, rent: 28, type: CellType.ASSET, color: '#008000', description: 'Фонд передовых технологий. Масштабирование автоматизированного интеллекта.', logoUrl: '/logos/brain.png' },
  { id: 35, name: 'WAVE', price: 200, rent: 25, type: CellType.ASSET, color: '#707070', description: 'Глобальная доставка контента. Минимизирует задержки во всех секторах.', logoUrl: '/logos/wave.png' },
  { id: 36, name: 'ВЗЛОМ', type: CellType.CHANCE, color: '#AF52DE', description: 'Утечка базы данных подтверждена. Выполняется дефрагментация учетных данных.', logoUrl: '/logos/vzlom.png' },
  { id: 37, name: 'HUB', price: 350, rent: 35, type: CellType.ASSET, color: '#000080', description: 'Централизованный гигант. Полный контроль над средствами и торгами.', logoUrl: '/logos/hub.png' },
  { id: 38, name: 'СКАМ', type: CellType.TAX, color: '#FF3B30', description: 'Обнаружений rug-pull. Ваш кошелек опустошен. Потеряно 150 токенов.', logoUrl: '/logos/scam.png' },
  { id: 39, name: 'PEER', price: 400, rent: 50, type: CellType.ASSET, color: '#000080', description: 'Чистая P2P торговля. Максимальный контроль и суверенитет над активами.', logoUrl: '/logos/peer.png' },
];
