import { Cell, CellType } from '../types/game';

export const BOARD_CELLS: Cell[] = [
  { id: 0, name: 'АИРДРОП', type: CellType.SPECIAL, description: 'Получите базовое вознаграждение. Впрыск ликвидности для всех участников сети.' },
  { id: 1, name: 'ТГ-КАНАЛ: МЕМЫ', price: 60, rent: 2, type: CellType.ASSET, color: '#8B4513', description: 'Высокая волатильность аудитории. Минимальные затраты на поддержку, базовый органический рост.' },
  { id: 2, name: 'ВЗЛОМ', type: CellType.CHANCE, color: '#AF52DE', description: 'Обнаружена уязвимость в системе. Инициирована случайная сетевая операция.' },
  { id: 3, name: 'ТГ-КАНАЛ: НОВОСТИ', price: 60, rent: 4, type: CellType.ASSET, color: '#8B4513', description: 'Стабильный поток трафика. Ценный актив для информационного арбитража.' },
  { id: 4, name: 'КОМИССИЯ СЕТИ', type: CellType.TAX, color: '#FF3B30', description: 'Обязательные расходы на поддержку инфраструктуры. Списание 200 токенов.' },
  { id: 5, name: 'ПРОКСИ-СЕРВЕР', price: 200, rent: 25, type: CellType.ASSET, color: '#707070', description: 'Ядро инфраструктуры. Увеличивает охват сети и ваше влияние.' },
  { id: 6, name: 'БОТ-ПАРСЕР', price: 100, rent: 6, type: CellType.ASSET, color: '#87CEEB', description: 'Инструмент автоматического сбора данных. Позволяет эффективно масштабировать операции.' },
  { id: 7, name: 'ИНСАЙД', type: CellType.CHANCE, color: '#AF52DE', description: 'Утечка конфиденциальной информации. Возможность для манипуляции рынком.' },
  { id: 8, name: 'ТОРГОВЫЙ БОТ', price: 100, rent: 6, type: CellType.ASSET, color: '#87CEEB', description: 'Алгоритмический модуль исполнения сделок. Генерирует стабильную микро-прибыль.' },
  { id: 9, name: 'СНАЙПЕР-БОТ', price: 120, rent: 8, type: CellType.ASSET, color: '#87CEEB', description: 'Функция опережения транзакций включена. Захват ранней ликвидности.' },
  { id: 10, name: 'ТЕНЕВОЙ БАН', type: CellType.SPECIAL, description: 'Алгоритмы пометили ваш аккаунт. Доступ к основной сети временно ограничен.' },
  { id: 11, name: 'NFT: ПАНКИ', price: 140, rent: 10, type: CellType.ASSET, color: '#FF69B4', description: 'Легендарная цифровая личность. Высокий статус в экосистеме.' },
  { id: 12, name: 'СЕРВЕРНАЯ СТОЙКА', price: 150, rent: 12, type: CellType.ASSET, color: '#FF69B4', description: 'Физические вычислительные мощности. Необходимы для тяжелых бэкенд-задач.' },
  { id: 13, name: 'NFT: ОБЕЗЬЯНЫ', price: 140, rent: 10, type: CellType.ASSET, color: '#FF69B4', description: 'Актив культуры "Ape-in". Представляет социальный капитал и доступ в закрытые группы.' },
  { id: 14, name: 'NFT: AZUKI', price: 160, rent: 12, type: CellType.ASSET, color: '#FF69B4', description: 'Утонченные эстетические токены. Высокая ценность в нишевых подсетях.' },
  { id: 15, name: 'VPN-УЗЕЛ', price: 200, rent: 25, type: CellType.ASSET, color: '#707070', description: 'Инфраструктура приватности. Необходима для работы в зонах ограниченного доступа.' },
  { id: 16, name: 'ДОМЕН: .TON', price: 180, rent: 14, type: CellType.ASSET, color: '#FF8C00', description: 'Нативная идентификация на платформе. Короткое, чистое и узнаваемое имя.' },
  { id: 17, name: 'ВЗЛОМ', type: CellType.CHANCE, color: '#AF52DE', description: 'Выполнение брутфорс-атаки... Анализ уязвимых конечных точек.' },
  { id: 18, name: 'ДОМЕН: .TELE', price: 180, rent: 14, type: CellType.ASSET, color: '#FF8C00', description: 'Упрощенная адресация. Высокий спрос со стороны институциональных игроков.' },
  { id: 19, name: 'ДОМЕН: .DAO', price: 200, rent: 16, type: CellType.ASSET, color: '#FF8C00', description: 'Имя, готовое к управлению. Критически важно для децентрализованных организаций.' },
  { id: 20, name: 'СЕРВЕРНЫЙ ХАБ', type: CellType.SPECIAL, description: 'Центральный узел пересечения трафика. Комиссия для верифицированных узлов отсутствует.' },
  { id: 21, name: 'DEX: SWAP', price: 220, rent: 18, type: CellType.ASSET, color: '#FF0000', description: 'Модуль децентрализованного обмена. Обеспечивает базовую торговую функциональность.' },
  { id: 22, name: 'ИНСАЙД', type: CellType.CHANCE, color: '#AF52DE', description: 'Прямая передача из ядра администрирования. Расшифровка данных...' },
  { id: 23, name: 'DEX: ЛИКВИДНОСТЬ', price: 220, rent: 18, type: CellType.ASSET, color: '#FF0000', description: 'Протокол автоматического маркет-мейкера. Жизненно важен для обмена активами.' },
  { id: 24, name: 'DEX: МОСТ', price: 240, rent: 20, type: CellType.ASSET, color: '#FF0000', description: 'Межсетевой конвейер. Позволяет перемещать цифровой капитал между сетями.' },
  { id: 25, name: 'ДАТА-ЦЕНТР', price: 200, rent: 25, type: CellType.ASSET, color: '#707070', description: 'Корпоративное хранилище. Содержит петабайты зашифрованных данных.' },
  { id: 26, name: 'LITE-МАЙНЕР', price: 260, rent: 22, type: CellType.ASSET, color: '#FFFF00', description: 'Энергоэффективная майнинг-ферма. Подходит для поддержания стабильного хешрейта.' },
  { id: 27, name: 'PRO-МАЙНЕР', price: 260, rent: 22, type: CellType.ASSET, color: '#FFFF00', description: 'Высокопроизводительные вычисления. Доминирует в обнаружении локальных блоков.' },
  { id: 28, name: 'ВЗЛОМ', type: CellType.CHANCE, color: '#AF52DE', description: 'Перехват сессии в процессе... Целевой игрок под воздействием эксплуатации.' },
  { id: 29, name: 'ASIC-МАЙНЕР', price: 280, rent: 24, type: CellType.ASSET, color: '#FFFF00', description: 'Специализированное оборудование для хеширования. Пиковая промышленная эффективность.' },
  { id: 30, name: 'ОБНАРУЖЕН', type: CellType.SPECIAL, description: 'Власти отследили ваш IP. Требуется немедленная релокация ресурсов.' },
  { id: 31, name: 'ФОНД: WEB3', price: 300, rent: 26, type: CellType.ASSET, color: '#008000', description: 'Капитал ранних стадий. Инвестирует в протоколы нового поколения.' },
  { id: 32, name: 'ФОНД: DEFI', price: 300, rent: 26, type: CellType.ASSET, color: '#008000', description: 'Фонд финансовых инноваций. Высокорисковые портфели с огромной доходностью.' },
  { id: 33, name: 'ИНСАЙД', type: CellType.CHANCE, color: '#AF52DE', description: 'Замечено движение "китов". Ожидается сильное влияние на рынок.' },
  { id: 34, name: 'ФОНД: AI', price: 320, rent: 28, type: CellType.ASSET, color: '#008000', description: 'Фонд передовых технологий. Масштабирование автоматизированного интеллекта.' },
  { id: 35, name: 'CDN-СЕТЬ', price: 200, rent: 25, type: CellType.ASSET, color: '#707070', description: 'Глобальная доставка контента. Минимизирует задержки во всех секторах.' },
  { id: 36, name: 'ВЗЛОМ', type: CellType.CHANCE, color: '#AF52DE', description: 'Утечка базы данных подтверждена. Выполняется дефрагментация учетных данных.' },
  { id: 37, name: 'CEX: БИРЖА', price: 350, rent: 35, type: CellType.ASSET, color: '#000080', description: 'Централизованный гигант. Полный контроль над средствами и торгами.' },
  { id: 38, name: 'СКАМ', type: CellType.TAX, color: '#FF3B30', description: 'Обнаружений rug-pull. Ваш кошелек опустошен. Потеряно 150 токенов.' },
  { id: 39, name: 'DEX: БИРЖА', price: 400, rent: 50, type: CellType.ASSET, color: '#000080', description: 'Чистая P2P торговля. Максимальный контроль и суверенитет над активами.' },
];
